version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.18
    steps:
      - checkout
      # Install dependencies using npm (with caching handled by the orb)
      - node/install-packages:
          pkg-manager: npm
      # Enforce deterministic CI install (uses package-lock.json)
      - run:
          name: Clean install
          command: npm ci
      - run:
          name: Run tests
          command: npm test

workflows:
  sample:
    jobs:
      - build-and-test
